In [2]:
import numpy as np

In [7]:
#1. Create a numpy array 1-9
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)


[1 2 3 4 5 6 7 8 9]


In [10]:
#2. Create 3x3 array of TRUES
#  True and False are represented in Python as 1 and 0
b = np.ones((3,3),dtype=bool)
print(b)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [23]:
#3. Extract all odd numbers from array 1-10
#is the number devisiable by 2 and print odd numbers
c = np.array([1,2,3,4,5,6,7,8,9,10])
d = np.where(c%2 == 0) # Find the indexes where the values are even
print(d)

(array([1, 3, 5, 7, 9], dtype=int64),)


In [24]:
#4. Replace all odd numbers with -1
e = np.array([1,2,3,4,5,6,7,8,9,10])
f = np.where(e%2 == 1) #Find the indexes where the values are odd
e[f] = -1 #replace with -1
print(e)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [ ]:
#5. Convert 1D array into 2D array with 2 rows
g=np.array([1,2,3,4,5,6,7,8])
print(g)
h = g.reshape(2,4)
print(h)

In [28]:
#6. Create 2 arrays i and j, stack vertically and calculate totals
i = np.arange(1,10).reshape(3,3)
print(i)
j = np.arange(10,19).reshape(3,3)
print(j)
k = np.dot(i, j) #multiplecatoin of the matrix
print(k)
l = np.sum (k) #total sum
print(l)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
1944


In [30]:
#7. Create the following pattern without hardcoding. 1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3
one = np.ones(3) #111
two = one + one #222
three = one * 3 #333

repeat = np.arange(1,4) #123
print(repeat)
tile = np.tile(repeat, 3) #repeats the array number of times specified
print(tile)

final = np.concatenate((one, two, three, tile))
print(final)

[1 2 3]
[1 2 3 1 2 3 1 2 3]
[1. 1. 1. 2. 2. 2. 3. 3. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.]


In [34]:
#8. Create 2 arrays, remove repeating numbers & combine
x = np.array([1,2,3,4,5])
y = np.array([4,5,6,7,8,9])
x = np.concatenate((x, y))
print(x)
x = np.unique (x) 
print(x)



[1 2 3 4 5 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [35]:
#9. Sum values of 3 to 7 together
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
c = np.concatenate((a, b))
d = c[(3 <= c) & (c < 7)]
print(d)
print(sum(d))

[3 4 5 4 5 6]
27
